### ISSUE TITLE
Use RxJS6 as main RxJS lib instead of needing to download rxjs-compat library

### ISSUE THREAD

**Issue by johannesschobel** [webfactorymk/ng2-canvas-whiteboard#30] opened 2018-08-08 15:12 UTC
Dear @Peshou ,

is it possible to use `rxjs 6` instead of `rxjs 5` for this package? Currently, if you want to use `rxjs 6` you will need to add the `compat lib`.. Wouldn't it be better to use `rxjs 6` as default and use a `compat` in case someone needs to use it with `rxjs 5` instead? because sooner or later one will need to switch to `rxjs 6`.

what do you think on this?

All the best and cheers,

**Comment by Peshou** [comment] 2018-08-13 14:15
Hey @johannesschobel, yes, it is better to use rxjs 6, but for the need of backwards compatibility for the release with premade shapes, I needed to ignore the rxjs change and allow all people to have access to the package with lower angular / rxjs versions, since changing the rxjs version would make me create a breaking changes version.

For the next release, this should be reversed, and the core should use rxjs 6, but everyone else should use rxjs-compat for the sake of old versions and compatibility.

**Comment by johannesschobel** [comment] 2018-08-13 15:01
yeah, but the `2.0` version was already a `major release` - therefore, i thought it would be good to introduce this "breaking change" (switch `rxjs`) in this course..

the next release (3.0) will be most likely some time away :disappointed:

**Comment by Peshou** [comment] 2018-08-15 14:05
Yeah, the problem is that if the canvas is using rxjs^5 and you are using rxjs^6, then you can use the compat lib and the canvas will work, but if it's the other way around, you will not be able to use the canvas, since your Angular rxjs^5 app will not be able to compile since it will not know where the imports to the rxjs 6 operators are and such.

That's why if the rxjs version is to be changed, then all the older apps and platforms will not be supported from that version onward.

For now I wanted to allow everyone to use the library. At some point soon I should completely rewrite the imports so that rxjs^6 will be used.

I will also change the name of this issue so that it describes the problem better.

Best Regards,
Stefan

**Comment by zijianhuang** [comment] 2018-09-13 03:01
Using rxjs-compat fixes the problem, sort of.

No Child Left Behind often also results in Every Children Left Behind.

Having to use rxjs-compat sounds like a penalty against developers who could always keep the dependencies up-to-date, in this case with rxjs 6. 

In software releases, we can do better. 

I myself also write components/tools for developers. So in the repository, I tagged the component with something like ForAngular4.2 and ForAngular5, especially for breaking changes in my component and major dependencies. And in Nuget, keep the older releases, and in the Readme.MD file, remind application developers to use older releases if they are still using older versions of Angular. 

It is generally advised to keep dependencies up-to-date for many good reasons. For those who can't enjoy the benefits of Angular 5 or 6 and upcoming 7, they should be able to use the older releases of ng-white-board in npm, along with older versions of Angular.

Don't you think this may be a more optimal balance?

**Comment by zijianhuang** [comment] 2018-09-14 00:38
Yesterday I had spent hours trying to make it work in my app on NG6, with rxjs-compat. Today, I try this component on NG6 Heroes Demo, not working either, then try it on NG5 Heroes Demo, then this component is working right away. Your @Peshou component is exactly what I need.  

I told my boss I may spend 1 day to fix this. And if not progressing well, I would have to wait for your working of moving to NG6.

So today, I will do something on the fork. And if progressing well, I may create a pull request. Or, if you @Peshou is doing similar thing right now, I would wait.

**Comment by zijianhuang** [comment] 2018-09-14 05:35
OK. I had created a fork and make this component wok well with Angular6/RXJS6, so far so good working in the Heroes NG6 demo. When this fork works well with my app, I will push it, likely next Monday.

**Comment by johannesschobel** [comment] 2018-09-14 06:20
It would be awesome if you could create a PR here

**Comment by zijianhuang** [comment] 2018-09-18 06:53
I had created a fork at https://github.com/zijianhuang/ng2-canvas-whiteboard

I don't think the fork is in production quality since I don't know how to bundle a module into a npm package, and I don't have time to learn such skills in near future. However, you @johannesschobel can still use the TS codes directly I am doing right now, and in the future you may still switch to the new release of ng2-canvas-whiteboard which then will support NG6.

And the fork works well now with my NG 6 app with Angular 6.1.7. I got stuck a little bit. While I had made the fork work well with the Heroes demo program on last Friday, it does not compile well with my app and the compiler kept complaining about Map<K, U, T> which I am not using such generic type anywhere in the app or in 3rd lib. After spending hours, I found that the Azure Storage js lib has Map<T..> defined but very different from Map<K,U> used in ng2-canvas-whiteboard. So I had hacked the type definition file of Azure Storage js lib a little bit, ng2-canvas-whiteboard works happily with my app, no rxjs-compat lib needed.

**Comment by johannesschobel** [comment] 2018-09-18 07:09
Hey @zijianhuang , thank you very much for your time and effort.. However, wouldn't it be better to specifically target the issue in this repository (e.g., create a new `ng6` branch)? What do you think @Peshou ?

**Comment by zijianhuang** [comment] 2018-09-18 08:00
@johannesschobel , only core member of the repository could create a branch, while other contributors like me could create forks and create PR. I made the fork so you can use the improvement with NG 6 before @Peshou could have time.

**Comment by johannesschobel** [comment] 2018-09-18 08:35
yeah, but you can provide a PR and send it to `master` branch.. @Peshou can then move the PR to another branch ;)

**Comment by zijianhuang** [comment] 2018-09-18 11:42
just done a PR, though I was expecting people just copy/paste from my fork. :) if they have urgent need for their Angular 6 app and dislike rxjs-compat.

**Comment by zijianhuang** [comment] 2018-09-19 10:46
@Peshou, from my dim memory, npm tool chains allow detection of dependencies. For example, if ng2-canvas-whiteboard 3.0 package with npm will check if other dependencies still include Rxjs 5 and Angular 4.x. If so, just raise a warning or stop installation of v3 if the programmers don't read the release note.

**Comment by Peshou** [comment] 2018-09-19 12:31
Okay the new version is v3.0.0, the new branch is origin/ng6. Please import it try it out and tell me if everything is okay since i have changed the way that the package is built, but using it should be the same as before for the end users.

**Comment by Peshou** [comment] 2018-09-19 12:32
Okay let me do that first and then I can publish the library version change

**Comment by Peshou** [comment] 2018-09-19 12:45
I will just add rxjs^6.0.0 as a peer dependency, so that will be the warning that's going to be raised.

**Comment by Peshou** [comment] 2018-09-19 12:47
Okay the version is 3.0.1, check it out please, the way the module is built was changed, but for end users everything should be the same, please check it out and give me some feedback if all is okay

**Closed** 2018-11-21 13:40 UTC
Labels: published
